apiVersion: networking.k8s.io/v1

kind: Ingress

metadata:
  name: nodejs-app-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /

spec:
  ingressClassName: nginx
  rules:
    - host: chipichapa.site
      http:
        paths:
          - path: /nodejs
            pathType: Prefix
            backend:
              service:
                name: nodejs-app-service
                port:
                  number: 80